nama=("zeti sarlina")
umur=int(("16"))
alamat=("sepit")
lulusan=("MA Almaarif Nurani Alikhlas")
agama=("Islam")
nim=("SI20230038")
tgl=("09 November 2007")

print("=="*10)
print("|   NAMA      :", nama    )
print("|   NIM       :", nim     )
print("|   UMUR      :", umur    )
print("|   TGL LAHIR :", tgl    )
print("|   ALAMAT    :", alamat  )
print("|   AGAMA     :", agama   )
print("|   LULUSAN   :", lulusan )
print("=="*10)